### ISSUE TITLE
No interface for retrieving concrete values from annotated terms

### ISSUE THREAD

**Issue by danmatichuk** [GaloisInc/what4#192]
If a concrete expression is annotated with `annotateTerm`, the resulting expression is no longer considered concrete according to `asConcrete`. This is probably expected (since otherwise those annotations might unexpectedly be simplified away), but the interface doesn't provide any way to retrieve the concrete value again.

One solution is to add a variant of `getAnnotation` that also retrieves the inner, un-annotated term, which would then again be considered concrete according to `asConcrete`.

**Comment by robdockins** [comment]
Adding a way to unwrap an annotated term and get the underlying term would be pretty easy, I think.
