### ISSUE TITLE
Test suites now take an hour to run after `flakes` update

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/what4#207]
After the `flakes` repo was updated to use `nixpkgs` 22.05 instead of 21.11 (see GaloisInc/flakes#3), the `what4` tests now take approximately one hour to run on CI, whereas before they took mere minutes. Compare the results of [this CI run before the `flakes` update](https://github.com/GaloisInc/what4/runs/7105286349?check_suite_focus=true#step:12:1) to the results of [this CI run after the `flakes` update](https://github.com/GaloisInc/what4/runs/7151039446?check_suite_focus=true#step:12:1), where the time it took to run the tests rose from 1m 55s to 1h 4m 45s. This is a pretty significant regression, so it would be worth figuring out what is causing this.

It's difficult to tell from the CI logs what is taking up so much time, but given that the `template_tests` test suite finishes last, that is where I decided to investigate. Some digging reveals some strange quirks about this `template_tests`, which I've chronicled in #206. It's not clear to me at the moment if #206 is related to the slowdown observed here, however.

**Comment by RyanGlScott** [comment]
In light of this, it would be worth pinning the commit of the `flakes` repo that we use in `what4`'s CI to make sure that we can revert back to a previous commit if need be.

**Comment by kquick** [comment]
Yup: because we build specific versions of the solvers rather than just "inheriting" whatever version is upstream, we have to incur the cost of the actual build until we cache it.

**Comment by kquick** [comment]
And no worries: I'd rather be intentional about monitoring this, so I'm fully aligned with our process on this!
