### ISSUE TITLE
cvc5 bug prevents `unsat-cores` and `produce-abducts` being turned on simultaneously

### ISSUE THREAD

**Issue by arjunvish** [GaloisInc/what4#214]
Currently, we deal with this by turning off unsat cores in cvc5. The release of `cvc5-1.0.2` (expected soon) will have a fix for this issue. Once its released and we update what4 to use it, we can turn on unsat cores again.

**Comment by RyanGlScott** [comment]
This was addressed in #213, which bumps the minimum required version of CVC5 to 1.0.2.
