### ISSUE TITLE
Make it build with ghc 9.4.3

### ISSUE THREAD

**Issue by yav** [GaloisInc/what4#224]
One problem at the moment is that we depend on `s-cargot` which has a restrictive dependency on `text`.

I file a ticket downstream:
https://github.com/aisamanra/s-cargot/issues/15

**Comment by RyanGlScott** [comment]
Other dependencies that will need to be updated:

* [ ] `parameterized-utils`
* [ ] `bv-sized`
* [ ] `bitwise`
