### ISSUE TITLE
`unknown sort` error for structs in foralls

### ISSUE THREAD

**Issue by jprider63** [GaloisInc/what4#24]
`what4` (bc44c3deeb001b737a1fe95dbba5a362acb56cf2) does not declare the sort for a struct used in a `forallPred` which causes an `unknown sort` error. Here is a minimal test case:

```
testForallStruct :: TestTree
testForallStruct = testCase "forall struct" $ withOnlineZ3 $ \sym s -> do
  let repr = viewSome (Some . BaseStructRepr) (Ctx.fromList [Some BaseBoolRepr])
  viewSome (\repr -> do
      var <- freshBoundVar sym (safeSymbol "v") repr
      p0 <- forallPred sym var (truePred sym)
      res <- checkSatisfiable s "test" p0
      isSat res  @? "sat"
    ) repr
```

Results in: 
```
    Exception: Solver reported an error:
      line 8 column 40: unknown sort 'Struct1'
    in response to command:
      (define-fun x!1 () Bool (forall ((x!0 (Struct1 Bool))) true))
```

My z3 version (on OS X): 
```
$ z3 --version
Z3 version 4.8.4 - 64 bit
```

**Comment by robdockins** [comment]
Thanks for the report.  Yeah, looks like we are forgetting to declare tuple sorts that occur in bound variable positions of `forall` and `exists` binders.  The invariant is supposed to be that we make sure tuples are declared as soon as they might come into scope, but we missed these cases.

**Comment by jprider63** [comment]
Thanks @robdockins! Your PR fixes this for me.
