### ISSUE TITLE
Please support versions >= 6.0.1

### ISSUE THREAD

**Issue by swt2c** [GaloisInc/what4#240]
Debian is updating to GHC 9.4 and LTS 21.9.  This brings in versions == 6.0.1, which isn't compatible with what4.  Could you add support for versions >= 6.0.1?

**Comment by RyanGlScott** [comment]
No problem. Let me know if you need a Hackage release with these changes. Otherwise, I will wait until the next scheduled `what4` release before doing so.

**Comment by swt2c** [comment]
> No problem. Let me know if you need a Hackage release with these changes. Otherwise, I will wait until the next scheduled `what4` release before doing so.

If the next scheduled release is a ways off (and it's not too much work on your part to make a release), a Hackage release would be appreciated.

**Comment by RyanGlScott** [comment]
I think I'll wait just a bit longer before making a new `what4` release, since a fix to https://github.com/fosskers/versions/issues/68 is imminent and will require a further update on `what4`'s end.

**Comment by fosskers** [comment]
Done and released as `6.0.2`.

**Comment by RyanGlScott** [comment]
Thanks, @fosskers! I've submitted #242 to use `versions >= 6.0.2` in `what4` so that we no longer have to define orphan instances.

**Comment by RyanGlScott** [comment]
I've uploaded [`what4-1.5.1`](https://hackage.haskell.org/package/what4-1.5.1) to Hackage with these changes.
