### ISSUE TITLE
Do bound variables need annotations?

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/what4#244]
The annotation mechanism (`annotateTerm`) attaches `Nonce`s to expressions via the `Annotation` constructor of `NonceApp`. [Bound variables](https://github.com/GaloisInc/what4/blob/076f49b996bd328764a9c6edece6b7c34cb1cfb4/what4/src/What4/Expr/App.hs#L664) already have associated `Nonce`s, their `bvarId`s. We should consider whether `annotateTerm`, when applied to a `BoundExpr`, should return the term as-is, and `getAnnotation` could just return the `bvarId`.

**Comment by RyanGlScott** [comment]
Yes, this seems wise. We already do something similar for `NonceAppExpr`s here:

https://github.com/GaloisInc/what4/blob/076f49b996bd328764a9c6edece6b7c34cb1cfb4/what4/src/What4/Expr/Builder.hs#L1640-L1643

**Comment by langston-barrett** [comment]
> We already do something similar for NonceAppExprs here:

I'm not sure this is analogous, actually - that case seems to be for `Annotation` expressions, which *are* explicitly annotated (unlike `BoundVarExpr`s, which are kind of "implicitly" annotated by virtue of already having a `Nonce`). However, we *could* probably special-case `NonceAppExpr` more generally in the same way - see #246.
