### ISSUE TITLE
Helpers for constructing bitvectors 0 and 1

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/what4#257]
It's common to construct literal bitvectors representing 0 or 1:

- https://github.com/search?q=repo%3AGaloisInc%2Fwhat4%20%2FbvLit.%2Bzero%2F&type=code
- https://github.com/search?q=repo%3AGaloisInc%2Fcrucible%20%2FbvLit.%2Bzero%2F&type=code
- https://github.com/search?q=repo%3AGaloisInc%2Fwhat4+%2FbvLit.%2Bone%2F&type=code
- https://github.com/search?q=repo%3AGaloisInc%2Fcrucible+%2FbvLit.%2Bone%2F&type=code

The best way to do that in the current interface is:
```haskell
bvLit sym w (BV.zero w)
bvLit sym w (BV.one w)
```
This is a bit of a pain, since you have to repeat the width repr, and to use functions from two separate packages. Instead, it might be nice to export
```
bvZero, bvOne :: IsSymInterface sym => NatRepr w -> IO (SymBV sym w)
```
The names also make the intent more obvious.

**Comment by sauclovian-g** [comment]
This is something of a drive-by comment because I don't know the context, but: if you have zero and one you almost always also want minusone too. Or allones, or some such name for that value.

**Comment by langston-barrett** [comment]
It looks like we have helpers for all of these except `bvOne` already:
```haskell
  -- | Return the bitvector of the desired width with all 0 bits;
  --   this is the minimum unsigned integer.
  minUnsignedBV :: (1 <= w) => sym -> NatRepr w -> IO (SymBV sym w)
  minUnsignedBV sym w = bvLit sym w (BV.zero w)

  -- | Return the bitvector of the desired width with all bits set;
  --   this is the maximum unsigned integer.
  maxUnsignedBV :: (1 <= w) => sym -> NatRepr w -> IO (SymBV sym w)
  maxUnsignedBV sym w = bvLit sym w (BV.maxUnsigned w)

  -- | Return the bitvector representing the largest 2's complement
  --   signed integer of the given width.  This consists of all bits
  --   set except the MSB.
  maxSignedBV :: (1 <= w) => sym -> NatRepr w -> IO (SymBV sym w)
  maxSignedBV sym w = bvLit sym w (BV.maxSigned w)

  -- | Return the bitvector representing the smallest 2's complement
  --   signed integer of the given width. This consists of all 0 bits
  --   except the MSB, which is set.
  minSignedBV :: (1 <= w) => sym -> NatRepr w -> IO (SymBV sym w)
  minSignedBV sym w = bvLit sym w (BV.minSigned w)
```
A related question, then, is whether it would be worth it to add "aliases" like `bvZero` for `minUnsignedBv`. This would have the downside of providing two names for the same function, but would have the upside of being more concise and potentially convey intent better.
