### ISSUE TITLE
Recover literal floats

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/what4#5]
We have the ability to recover literal values from `SymExpr`s for with `asNat`, `asUnsignedBV`, `asSignedBV`, `asConstantPred`, etc. Is the same thing possible for floats? Could we extract the values of `iFloatLit` back out? This is a complex question due in part to our various possible interpretations for floating point values (uninterpreted, real, IEEE-754).  

Some applications of this would be to pretty-printing and to constant folding.

**Comment by robdockins** [comment]
Fixed via #89
