### ISSUE TITLE
Initial Hackage release

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/what4#57]
This is a tracking ticket to collect together all the administrivia tasks preceding the 1.0 package release.

Tasks:
- [x] Write a reasonable README 
- [x] Start a CHANGELOG
- [x] Check on the status of Hackage documentation, fix any glaring errors/omissions
- [x] Double check `.cabal` package bounds and update metadata
- [x] Tutorial ?
- [x] Document required/recommended solver versions
- [x] Update copyright notices, license metadata and module headers

**Comment by benjaminselfridge** [comment]
FYI: https://github.com/GaloisInc/what4/tree/readme-tutorial

This is a WIP, but I hope to have something reasonable finished by early next week.

**Comment by robdockins** [comment]
@benjaminselfridge, thanks for taking a crack at that!

**Comment by robdockins** [comment]
Finished:

http://hackage.haskell.org/package/what4-1.0
