### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by david-a-wheeler** [GaloisInc/what4#64]
Can you please make it clear with the license is? [Hackage says the license is BSD-3-Clause](https://hackage.haskell.org/package/what4), that the license is not obvious when looking at this GitHub repository. Maybe simply put the license text of BSD-3-Clause into a file named LICENSE ?

Thanks!

**Comment by robdockins** [comment]
You can find LICENSE files associated with each package subdirectory, e.g.
https://github.com/GaloisInc/what4/blob/master/what4/LICENSE
