### ISSUE TITLE
Test failure with Z3 4.8.9

### ISSUE THREAD

**Issue by felixonmars** [GaloisInc/what4#67]
```
  Z3 string4:                              FAIL (0.13s)
    test/ExprBuilderSMTLib2.hs:794:
    substring not found
...
1 out of 54 tests failed (4.27s)
Test suite expr-builder-smtlib2: FAIL
```

All other tests pass. With Z3 4.8.8 and everything else unchanged the tests pass.

**Comment by robdockins** [comment]
Thanks for the report.  It seems like something has changed in Z3's string support for that release; I'll take a look and see what's going on.

**Comment by robdockins** [comment]
Turns out, this was a problem with the test, which was incorrectly rejecting some models.
