### ISSUE TITLE
Document bounds order for freshBounded*

### ISSUE THREAD

**Issue by georgefst** [GaloisInc/what4#69]
The [docs](https://hackage.haskell.org/package/what4-1.0/docs/What4-Interface.html#t:IsSymExprBuilder) for `freshBoundedInt` etc. don't make it clear which argument is the upper bound and which the lower. Lower being first is indeed more intuitive, but the docs say *upper and lower*, which introduces enough doubt that I had to actually run some tests to verify this.

**Comment by robdockins** [comment]
That is an unfortunate ambiguity.  I'll fix the docs.
