### ISSUE TITLE
fmax and fmin semantics

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/what4#87]
The `fp.min` and `fp.max` operations of the SMTLib2 theory of IEEE 754 arithmetic are underspecified WTR to the result when passed in two zeros (of potentially differing signs).  The actual IEEE spec itself is underspecified as to which signedness of zero will be returned (CF http://smtlib.cs.uiowa.edu/papers/BTRW14.pdf)

This is, as far as I know, the only place where some "core" operations of the theory are not fully specified (most of the transcendental functions, however, are underspecified WRT the amount of precision they are required to produce).

This is an extremely annoying corner case, but I think we need to deal with it somehow, as solvers actually produce observably different behaviors, as do actual implementations.  This could, in principle, yield a soundness issue.

Moreover, `Z3` actively punts on this issue by considering, e.g., `fp.min (-zero, +zero)` to be a value form and will return syntax for this when asked to evaluate values in a model.  Our value parsing code can't properly handle these non-standard syntactic forms.

**Comment by robdockins** [comment]
After some discussion, I've decided to make `floatMin` and `floatMax` nondeterministic in the corner case by explicitly choosing a fresh boolean variable that is consulted to determine which value to return.  This means that different applications of `floatMin` to the same inputs could result in different outputs.  This retains soundness, but may make equivalence proofs harder.  The alternative is to use uninterpreted functions to determine the sign of the output in the corner case, but this requires considerably more infrastructure to drag around the needed function declarations.

**Comment by kiniry** [comment]
Why not make it nondeterministic in the semantics but deterministic in
practice?  I.e., the concrete value chosen at the first application is
uniformly used throughout the rest of a given invocation of any tool?  This
is what we did in these corner cases in the JML semantics.

**Comment by robdockins** [comment]
I'm not convinced that would be sound.  In particular, you could prove a property about a program that wouldn't hold on an actual program run because you happened to chose the "wrong" concrete behavior.  In the linked paper, they note that, e.g., an x87 floating point unit may give different answers in this corner case than the similar AVX instruction, even on the same chip (!), so the distinction actually arises in practice.  Because the sign bit is observable (via `copysign` or bitcasting to integers), I think we have to be conservative here.

**Comment by kiniry** [comment]
I hadn't realized that there are different behaviorals realized across a
single SoC.  That's crazy.  That's not the framing we had for the past
semi-related work.

**Comment by robdockins** [comment]
Implemented via #89
