### ISSUE TITLE
structs containing nats don't get represented correctly

### ISSUE THREAD

**Issue by benjaminselfridge** [GaloisInc/what4#91]
When I create a struct with a single `Nat` field, the constraint that the field is positive does not get output to the solver. I only found this because it resulted in an arithmetic underflow in certain cases.

See https://gist.github.com/benjaminselfridge/b55319660c6dd0609f1c17329abc4cb8

**Comment by benjaminselfridge** [comment]
The same problem also exists for arrays.

I think the problem is here: https://github.com/GaloisInc/what4/blob/master/what4/src/What4/Protocol/SMTWriter.hs#L1225

Perhaps a special case is required for structs and arrays when there is no abstract domain?

**Comment by robdockins** [comment]
Closed via #97
